export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const GET_COUNTRY_BY_QUERY = "GET_COUNTRY_BY_QUERY";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const POST_ACTIVITY = "POST_ACTIVITY";
export const PUT_ACTIVITY = "POST_ACTIVITY";
export const DELETE_ACTIVITY = "POST_ACTIVITY";
